name: Trigger Airflow DAG on Dev Branch

# Trigger the workflow when there's a push to the "main" branch
on:
  push:
    branches:
      - main  # Workflow is triggered on a push to the "main" branch

# Define jobs in the workflow
jobs:
  trigger_dag:
    runs-on: ubuntu-latest  # Define the base operating system
    
    # Define the steps for the job
    steps:
      # Step 1: Check out the repository codebase
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Validate the DAG structure or other checks
      - name: Validate DAG
        run: |
          # Perform DAG validation, e.g., syntax check or other checks
          echo "Validating the DAG..."

      # Step 3: Trigger the Airflow DAG
      - name: Trigger Airflow DAG
        run: |
          # Make a request to trigger the DAG in Airflow
          # Use GitHub Secrets to secure sensitive information

          response=$(curl -G -X GET "${{secrets.AIRFLOW_API_URL_RUN_DAG}}" \
              --data-urlencode "dag_name=sales_data_extraction" \
              --data-urlencode "username=${{secrets.AIRFLOW_USERNAME}}" \
              --data-urlencode "password=${{secrets.AIRFLOW_PASSWORD}}" \
              -H "x-api-key: ${{secrets.AIRFLOW_TOKEN}}" )

          dag_id=$(echo $response | jq -r '.dag_id')
          dag_run_id=$(echo $response | jq -r '.dag_run_id')

          #sleep 1 sec for api limit
          


      # Step 4: Trigger the Airflow DAG
      - name: Check Airflow DAG status
        run: |
          # Make a request to check the DAG status in Airflow
          echo "DAG ID: $dag_id"
          echo "DAG Run ID: $dag_run_id"
          
          response=$(curl -G -X GET "${{secrets.AIRFLOW_API_URL_CHECK_DAG_STATUS}}" \
              --data-urlencode "dag_name=$dag_id" \
              --data-urlencode "dag_run_id=$dag_run_id" \
              --data-urlencode "username=${{secrets.AIRFLOW_USERNAME}}" \
              --data-urlencode "password=${{secrets.AIRFLOW_PASSWORD}}" \
              -H "x-api-key: ${{secrets.AIRFLOW_TOKEN}}" )
          echo $response


          
      
   
