name: Trigger Airflow DAG on Dev Branch

# Trigger the workflow when there's a push to the "main" branch
on:
  push:
    branches:
      - main  # Workflow is triggered on a push to the "main" branch

# Define jobs in the workflow
jobs:
  trigger_dag:
    runs-on: ubuntu-latest  # Define the base operating system
    
    # Define the steps for the job
    steps:
      # Step 1: Check out the repository codebase
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Validate the DAG structure or other checks
      - name: Validate DAG
        run: |
          # Perform DAG validation, e.g., syntax check or other checks
          echo "Validating the DAG..."

      # Step 3: Trigger the Airflow DAG
      - name: Trigger Airflow DAG
        run: |
          # Make an HTTP POST request to trigger the DAG in Airflow
          # Use GitHub Secrets to secure sensitive information
          curl POST "${{secrets.AIRFLOW_API_URL_RUN_DAG}}" \
          -H "x-api-key:${{secrets.AIRFLOW_TOKEN}}"
          -d "dag_name=sales_data_extraction" \
          -d "username=${{secrets.AIRFLOW_USERNAME}}" \
          -d "password=${{secrets.AIRFLOW_PASSWORD}}" 
          
      
   
