name: Trigger Airflow DAG on Dev Branch

# Trigger the workflow when there's a push to the "main" branch
on:
  push:
    branches:
      - main  # Workflow is triggered on a push to the "main" branch

# Define jobs in the workflow
jobs:
  trigger_dag:
    runs-on: ubuntu-latest  # Define the base operating system
    
    # Define the steps for the job
    steps:
      # Step 1: Check out the repository codebase
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Validate the DAG structure or other checks
      - name: Validate DAG
        run: |
          # Perform DAG validation, e.g., syntax check or other checks
          echo "Validating the DAG..."

      # Step 3: Trigger the Airflow DAG
      - name: Trigger Airflow DAG
        run: |
          # Make a request to trigger the DAG in Airflow
          # Use GitHub Secrets to secure sensitive information
          curl -G -X GET "https://4eum8q7emc.execute-api.eu-central-1.amazonaws.com/v1/airflow/run_dag" \
          --data-urlencode "dag_name=sales_data_extraction" \
          --data-urlencode "username=airflow" \
          --data-urlencode "password=airflow" \
          -H "x-api-key: N7wmz1I2tx6WvkZzyuNcs4E30lhidqyI2mF5DmKP"
          
      
   
